name: Java CI

on: 
  push:
    branches:
      - master
      - unit-testing
      - github-actions
  pull_request:
    branches:
      - master
      - unit-testing

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout LeapJna
      uses: actions/checkout@v2
      with:
        path: 'LeapJna'
    - name: Checkout MockLeapC
      uses: actions/checkout@v2
      with:
        repository: 'komposten/MockLeapC'
        path: 'MockLeapC'
        token: ${{ secrets.GH_TOKEN }}
    - name: Build MockLeapC
      run: |
        cmake -S MockLeapC/. -B MockLeapC/out/build
        cmake --build MockLeapC/out/build --config Release
    - name: Copy MockLeapC.dll to LeapJna/lib
      run: |
        MKDIR LeapJna\lib\win32-x86-64
        COPY MockLeapC\out\build\Release\MockLeapC.dll LeapJna\lib\win32-x86-64
        TREE LeapJna\lib /F
    - name: Build with Maven
      run: |
        CD LeapJna
        mvn -B package --file pom.xml
