name: Java CI

on: 
  push:
    branches:
      - master
      - unit-testing
      - github-actions
  pull_request:
    branches:
      - master
      - unit-testing

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout MockLeapC
      uses: actions/checkout@v2
      with:
        repository: 'komposten/MockLeapC'
        token: ${{ secrets.GH_TOKEN }}
    - name: Build MockLeapC
      run: |
        cmake -S . -B ./out/build
        cmake --build ./out/build --config Release
    - name: Checkout LeapJna
      uses: actions/checkout@v2
    - name: Copy MockLeapC.dll
      run: |
        MKDIR lib\win32-x86-64
        COPY ..\MockLeapC\out\build\Release\MockLeapC.dll lib\win32-x86-64
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
