name: Create release

on:
  create
  
jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout LeapJna
      uses: actions/checkout@v2
        
    - name: Get ref type
      id: ref_type
      run: |
        .github/scripts/check_tag.sh
    
    - name: Create release
      if: steps.ref_type.outputs.ref_type == 'release_tag'
      run: |
        VERSION=${GITHUB_REF##*/}
        hub release create -m "$VERSION" $VERSION
    
    - name: Skip release
      if: steps.ref_type.outputs.ref_type != 'release_tag'
      run: |
        echo "Ref is not a release tag, skipping."
